export type HydrationSeverity = 'info' | 'warn' | 'error';

/**
 * Snapshot emitted whenever React reports a recoverable hydration mismatch.
 */
export interface HydrationSnapshot {
    route: string;
    serverAttributes: Record<string, string>;
    clientAttributes: Record<string, string>;
    extensionFingerprint?: string;
    timestamp: string;
    correlationId: string;
    severity: HydrationSeverity;
}

export type NetworkProfile = 'normal' | 'slow-3g' | 'offline';
export type ExtensionProfile = 'none' | 'fusion-mock' | string;

/**
 * Structured artifact generated by the dashboard hydration regression test.
 */
export interface DashboardRenderCheck {
    hasMismatch: boolean;
    warnings: string[];
    networkProfile: NetworkProfile;
    extensionProfile: ExtensionProfile;
    screenshotPath?: string;
    durationMs: number;
}
